### ISSUE TITLE
Change Authorization Model Spec to support further policy mode like ABAC and so on.

### ISSUE THREAD

**Issue by aru-amedeo** [eu-sovereign-cloud/spec#43]
Change Authorization Scheme to support further policy mode like below

```
      x-authorization:
        type: hybrid  # Supports both RBAC and ABAC
        policies:
          - type: RBAC
            scopes: ["*"]
            resources: ["seca.compute/instances/*"]
            verbs: ["list"]
          - type: ABAC
            attributes:
              - name: workspace
                description: Workspace in the request must match user's allowed namespaces.
              - name: user-roles
                description: User must have a role allowing access to the resource.
              - name: request-time
                description: Access allowed only during specific time windows. 
```
